<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter

In [1]:
import pandas as pd
import psycopg2

In [2]:
# вставьте сюда параметры подключения из юнита 1. Работа с базой данных из Python 

DBNAME = 'project_sql'
USER = 'skillfactory'
PASSWORD = 'cCkxxLVrDE8EbvjueeMedPKt'
HOST = '84.201.134.129'
PORT = 5432

In [3]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies).

In [4]:
# текст запроса
query_3_1 = f'''select *
    from public.vacancies
    '''

In [5]:
# результат запроса
df = pd.read_sql_query(query_3_1, connection)
df.info()
#df['id'].count() - либо можно вывести количество вакансий числом

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\720433011.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_1, connection)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49197 entries, 0 to 49196
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           49197 non-null  int64
 1   name         49197 non-null  object
 2   key_skills   40741 non-null  object
 3   schedule     49197 non-null  object
 4   experience   49197 non-null  object
 5   employment   49197 non-null  object
 6   salary_from  21485 non-null  float64
 7   salary_to    12690 non-null  float64
 8   area_id      49197 non-null  int64
 9   employer_id  49197 non-null  int64
dtypes: float64(2), int64(3), object(5)
memory usage: 3.8+ MB

2. Напишите запрос, который посчитает количество работодателей (таблица employers).

In [6]:
# текст запроса
query_3_2 = f'''select *
    from public.employers
    '''

In [7]:
# результат запроса
df = pd.read_sql_query(query_3_2, connection)
#df
df['id'].count()

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\1588513963.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_2, connection)

np.int64(23501)

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [8]:
# текст запроса
query_3_3 = f'''select *
    from public.areas
    '''

In [9]:
# результат запроса
df = pd.read_sql_query(query_3_3, connection)
#df
df['id'].count()

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\645928164.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_3, connection)

np.int64(1362)

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [10]:
# текст запроса
query_3_4 = f'''select *
    from public.industries
    '''

In [11]:
# результат запроса
df = pd.read_sql_query(query_3_4, connection)
#df
df['id'].count()

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\725852229.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_4, connection)

np.int64(294)

***

In [ ]:
# выводы по предварительному анализу данных
# 1. Количество вакансий больше примерно в 2 с небольшим раза чем работодателей. С одной стороны можно предположить, что штаты предприятий достаточно хорошо укомплектованы, 
# с другой стороны у 5-и работодателей может быть потребность в 5 сотрудниках на всех, а у 1-ого предприятия потребность в 10 сотрудниках. 
# Требуется более детальный анализ по отраслям и ниаменованиям позиций.
# 2. Учитывая, что работодатели представлены в 1 362 регионах это говорит о большом географическом охвате, т.е. практически на всей территории страны.
# 3. Вакансии представлены в 294 различных направлений это свидетельствует также о большом охвате практически всех отраслей промышленности, услуг, торговли и т.п.

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [ ]:
# текст запроса
# Здесь применил соединение 2-х таблиц по ключам используя оператор INNER JOIN. Слово INNER в операторе упустил, т.к. JOIN то тоже самое, что и INNER JOIN. 
query_4_1 = f'''select
    a.name as "region",
    count (v.id) as "cnt"
from
    public.vacancies v
    join public.areas a on v.area_id = a.id
group by region
order by cnt DESC
limit 10
    '''

In [13]:
# результат запроса
df = pd.read_sql_query(query_4_1, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\2457173557.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_1, connection)

            region   cnt
0           Москва  5333
1  Санкт-Петербург  2851
2            Минск  2112
3      Новосибирск  2006
4           Алматы  1892
5     Екатеринбург  1698
6  Нижний Новгород  1670
7           Казань  1415
8        Краснодар  1301
9           Самара  1144

2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [ ]:
# текст запроса
# В данно случае применил фильтрацию, а затем подсчет
query_4_2 = f'''select
    count(v.id) as "cnt"
from
    public.vacancies v
where salary_from is not NULL or salary_to is not NULL
    '''

In [15]:
# результат запроса
df = pd.read_sql_query(query_4_2, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\970655580.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_2, connection)

     cnt
0  24073

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [ ]:
# текст запроса
# Применил одну из агрегатных функций AVG
query_4_3 = f'''select
    round(AVG(v.salary_from), 0) as "from",
    round(AVG(v.salary_to), 0) as "to"
from
    public.vacancies v
    '''

In [17]:
# результат запроса
df = pd.read_sql_query(query_4_3, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\2500607024.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_3, connection)

      from        to
0  71065.0  110537.0

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.

In [27]:
# текст запроса - Вариант 1 - в "лоб" неочень красивый запрос
query_4_4 = f'''select
    v.schedule as "schedule",
    count(v.schedule) as "cnt_sch",
    v.employment as "employment",
    count(v.employment) as "cnt_eml"
from
    public.vacancies v
group by schedule, employment
order by 2 DESC, 4 DESC
limit 7
    '''

In [18]:
# текст запроса Вариант 2 - оптимальный
query_4_4 = f'''select
    v.schedule as "schedule",
    v.employment as "employment",
    count(v.id) as "cnt"
from
    public.vacancies v
group by schedule, employment
order by 3 DESC
limit 7
    '''

In [19]:
# результат запроса
df = pd.read_sql_query(query_4_4, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\2022935265.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_4, connection)

           schedule           employment    cnt
0       Полный день     Полная занятость  35367
1  Удаленная работа     Полная занятость   7802
2     Гибкий график     Полная занятость   1593
3  Удаленная работа  Частичная занятость   1312
4    Сменный график     Полная занятость    940
5       Полный день           Стажировка    569
6    Вахтовый метод     Полная занятость    367

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта.

In [21]:
# текст запроса
# Применил группировку по опыту, посчитал вакансии и осортировал по возрастанию
query_4_5 = f'''select
    v.experience as "experience",
    count(v.id) as "cnt"
from
    public.vacancies v
group by experience
order by "cnt" ASC
    '''

In [22]:
# результат запроса
df = pd.read_sql_query(query_4_5, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\2316260449.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_5, connection)

           experience    cnt
0         Более 6 лет   1337
1           Нет опыта   7197
2       От 3 до 6 лет  14511
3  От 1 года до 3 лет  26152

***

In [ ]:
# выводы по детальному анализу вакансий
# 1-Подавляющее количество вакансий приходится на столицу Москву и второй по величине в РФ город Санкт-Петербург. При этом Москва имеет большой отрыв от Санкт-Петербургом. 
# Далее тенденция, города миллионики и на понижение.

# 2-Поля с зарплатой заполнены приблизетельно на половину и преобладает доля полей с заполненными значения - от, 
# что в полне объяснимо - обсуждением 'верхней граниицы' ЗП по итогам собеседования.

# 3-Cредние значения для нижней и верхней границы зарплатной вилки имеет большой диапазон. 
# Нижняя граница в среднем на 55 % меньше верхней границы. Т.е. работодатель потенциально готов платить за навыки. 
# Но здесь требуется изучит эту разницу в разрезе городов (возможно на Москву, С-ПБ, Минск - приходится основной объем)

# 4-В части типа рабочего графика и трудоустройства на данный момент преобладет формат - очно и полный день, 
# но с хорошей долей занимает 2- место - удаленная работа и полная занятость (есть потенциал роста данного формата). 
# Это самые востребованные варианты. Далее идет резкое снижение.

# 5-В части требуемого опыта первое место по объему занимает самый базовый опыт (можно предположить, что есть заинтересованность в молодых кадрах и сформировать под себя), 
# 2 место - с большим снижением по количеству занимает - потребность в опытных сотрудниках, на 3-ем месте без опыта, т.е. опять наблюдаем тенденцию в потребности молодых кадров,
# 4 место - логично имеет меньший объем по количеству, т.к. там потребность в экпертах, а их по умолчанию ограниченное количество.

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [ ]:
# текст запроса
# Здесь применил соединение 2-х таблиц по ключам используя оператор JOIN. Затем группировка работодателям и сортировка по убыванию.
query_5_1 = f'''select
    e.name as "name",
    count(v.id) as "cnt"
from
    public.employers e
    join public.vacancies v on e.id = v.employer_id
group by e.name
order by "cnt" DESC
limit 5
    '''

In [24]:
# результат запроса
df = pd.read_sql_query(query_5_1, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\3834399874.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_1, connection)

            name   cnt
0         Яндекс  1933
1     Ростелеком   491
2       Тинькофф   444
3           СБЕР   428
4  Газпром нефть   331

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.

In [26]:
# текст запроса
# За основу взял таблицу areas и используя left join соединил сначала с таблицей vacancies, а затем с таблицей employers. 
# Применил фильтр и сортировку (от большего к меньшему) и ограничил 5-ю строками в выводе.
query_5_2 = f'''select
    a.name as "name",
    count(v.id) as "cnt_vac",
    count(e.id) as "cnt_empl"
from
    public.areas a
    left join public.vacancies v on a.id = v.area_id
    left join public.employers e on a.id = e.area  
group by a.name
having count(v.id) = 0
order by count(e.id) DESC 
limit 5
    '''
    
# P.S. 
# 1. использовал left join - что-бы сохранить все регионы
# 2. left join public.employers e on a.id = e.area - применен ключ - e.area - он неявно выражен

In [27]:
# результат запроса
df = pd.read_sql_query(query_5_2, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\2250345976.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_2, connection)

                 name  cnt_vac  cnt_empl
0              Россия        0       410
1           Казахстан        0       207
2  Московская область        0        75
3  Краснодарский край        0        19
4            Беларусь        0        18

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.

In [30]:
# текст запроса
# Применил соединение 2-х таблиц по ключам используя оператор LEFT JOIN. При подсчете регионов учел уникальность по регионам при помощи DISTINCT. 
# Затем группировка по id-работодателей и сортировка по количеству по убыванию.   
query_5_3 = f'''select
    e.name as "name",
    count(distinct v.area_id) as "cnt_areas"
from
    public.employers e
    left join public.vacancies v on e.id = v.employer_id 
group by e.id
order by 2 desc
limit 5 
    '''

In [31]:
# результат запроса
df = pd.read_sql_query(query_5_3, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\201667002.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_3, connection)

                     name  cnt_areas
0                  Яндекс        181
1              Ростелеком        152
2              Спецремонт        116
3  Поляков Денис Иванович         88
4               ООО ЕФИН          71

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности.

In [32]:
# текст запроса
# Применил соединение 2-х таблиц по ключам используя оператор LEFT JOIN. Далее фильтр по признаку industry_id где значения NULL. 
query_5_4 = f'''select
    count(e.id) as "cnt_empl"
from
    public.employers e
    left join public.employers_industries ei on e.id = ei.employer_id
where ei.industry_id IS NULL
    '''

In [33]:
# результат запроса
df = pd.read_sql_query(query_5_4, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\3493105328.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_4, connection)

   cnt_empl
0      8419

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности.

In [50]:
# текст запроса
# Применил соединение 2-х таблиц по ключам используя оператор LEFT JOIN. Далее группировка по id-компаний и фильтр по количеству так же по признаку id-компаний. 
query_5_5 = f'''select
    e.name as "name company",
    count(e.id) as "cnt_empl"
from
    public.employers e
    left join public.employers_industries ei on e.id = ei.employer_id
group by e.id
having count(e.id) = 4
order by e.name ASC 
limit 5
    '''

In [48]:
# Вариант 2 - Отличие в в фильрации применил признак employer_id из таблицы employers_industries
query_5_5 = f'''select
    e.name as "name company",
    count(ei.employer_id) as "cnt_empl"
from
    public.employers e
    left join public.employers_industries ei on e.id = ei.employer_id
group by e.id
having count(ei.employer_id) = 4
order by e.name ASC 
limit 5
    '''

In [51]:
# результат запроса
df = pd.read_sql_query(query_5_5, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\388711819.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_5, connection)

   name company  cnt_empl
0  101 Интернет         4
1      21vek.by         4
2          2ГИС         4
3            2К         4
4   4 пикселя +         4

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.

In [54]:
# текст запроса
# За основу взял таблицу employers_industries, поскольку она имеет ключи и для таблицы employers и для таблицы industries. Затем соединил их. Далее фприменил фильтр.
query_5_6 = f'''select
    count(e.id) as "cnt_areas"
from
    public.employers_industries ei
    left join public.employers e on e.id = ei.employer_id
    left join public.industries i on i.id = ei.industry_id  
where i.name = 'Разработка программного обеспечения'
    '''

In [55]:
# результат запроса
df = pd.read_sql_query(query_5_6, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\821628714.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_6, connection)

   cnt_areas
0       3553

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8). 

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API.

In [ ]:
# код для получения списка городов-милионников

In [56]:
# текст запроса
# Применил соединение 3-х таблиц по ключам используя оператор LEFT JOIN. Далее фильтрация, группировка и сортировка по возрастанию.
# Да, немного отклонился от задания прописал вручную список городов-миллионииков и применил оператор IN совместо с условием фильтрации по компании Яндекс.
# так же при помощи объединения union all вывел обобщенные данные по количеству.
query_5_7 = f''' (select 
    a.name as "name_area", 
    count(v.id) as "vacancy_count"
from 
    public.areas a
    left join public.vacancies v on v.area_id = a.id
    left join public.employers e on e.id = v.employer_id
where e.name = 'Яндекс' 
    and a.name in ('Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург', 'Нижний Новгород', 'Казань', 'Челябинск', 'Самара', 'Омск', 'Ростов-на-Дону', 
    'Уфа', 'Красноярск', 'Пермь', 'Воронеж', 'Волгоград', 'Краснодар')
group by a.name
order by count(v.id) ASC)

union all

(select 
    'Total', 
    count(v.id)
from 
    public.areas a
    left join public.vacancies v on v.area_id = a.id
    left join public.employers e on e.id = v.employer_id
where e.name = 'Яндекс' and a.name in ('Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург', 'Нижний Новгород', 'Казань', 'Челябинск', 'Самара', 'Омск', 'Ростов-на-Дону', 
    'Уфа', 'Красноярск', 'Пермь', 'Воронеж', 'Волгоград', 'Краснодар'))
order by 2 ASC
'''

In [57]:
# результат запроса
df = pd.read_sql_query(query_5_7, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\1965596796.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_7, connection)

          name_area  vacancy_count
0              Омск             21
1         Челябинск             22
2        Красноярск             23
3         Волгоград             24
4    Ростов-на-Дону             25
5             Пермь             25
6            Казань             25
7               Уфа             26
8            Самара             26
9         Краснодар             30
10          Воронеж             32
11      Новосибирск             35
12  Нижний Новгород             36
13     Екатеринбург             39
14  Санкт-Петербург             42
15           Москва             54
16            Total            485

***

In [ ]:
# выводы по анализу работодателей
# 1. В первой пятерке работодателей по количеству ванкансий мы наблюдаем IT-отрасль, телекоммуникационную, банковский сектор, добыча/транспортировка природных ресурсов. 
# Во многом эти компании цифровые и все они ферального масштаба. Поэтому потребность в IT-специалистах высока. 
# На этом фоне пятерку замыкает Газпром - безусловно эта также высокотехнологичная сфера, 
# но предполагаю что в данную компанию iT- специалисты требуется в меньшей степени (скорее всего судя по объму вакансий это больше линейный персонал).

# 2.Наибольшее количество работодателей мы набладаем в Москве, далле с отставанием примерно в 2 раза идет Казахстан и затем с большим отрывом все остальные. 
# Мы отчетливо видим высокую концентрацию работодателей в Москве и Казастане, но при этом сами компании ищут сотрудников в других регионах, 
# т.е. компании могут вести свою фактическую деятельность в других регионах, либо имея возможность удаленного режима работы увеличивают охват сосикателей и экономят на ЗП. 

# 3. В части распределения по регионам в лидерах IT-сфера и телекоммуникации (стоит отметить, что данные отрасли хорошо подходят для удаленной работы, 
# что открывает больше возможностей как для работодателей, так и для соискателей). 
# Далее по всей видимости расположились компании по обслуживанию оборудования / инфроструктуры 
# (но здесь нужно отделно проверить по сфере деятельности и/или вакансиям, чтобы однозназно сделать выводы).

# 4. Более 1/3-и, а именно около 36% работодателей не указали свою сферу деятельности. 
# Нужно разбираться в причинах, почему не указали: неудобно заполнять анкету, не хотят заполнять или иное Это важно, 
# это влияет на качество поиска вакансий и на формирование предложений соискателям.

# 5. Здесь больше отработка навыков по написанию запросов. Существенной полезной информации не получено (для галочки первая 5-ка это все IT-компании).

# 6. Порядка 15% от бщего количества работодателей в качестве своей сферы деятельности указали Разработка программного обеспечения. 
# В настоящий момент эта доля уже немаленькая и учитывая темпы развития ПО и потребность в своем ПО можно предположить, что эта доля будет расти. 
# Но по хорошему конечно нужно исследовать этот показатель в динамике.

# 7. Основной запрос сосредоточен в городах далеко за миллион это - Москва и С-Пб. Далее идет плавное снижение количества вакансий по мере снижения численности населения. 
# Здесь четко прослеживается зависимость количество ваканчий от численности города.

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.*

In [ ]:
# текст запроса
# Производил фильтрацию можно сказать 'вручную'
query_6_1 = f'''select
    v.name as "name_vac",
    count(v.name) as "cnt_vac"
from
    public.vacancies v
WHERE v.name LIKE '%данн%' 
    or v.name LIKE '%data%'
    or v.name LIKE '%ДАНН%' 
    or v.name LIKE '%DATA%'
    or v.name LIKE '%Data%'
    or v.name LIKE '%Данн%'
group by v.name 
    '''

In [58]:
# Вариант 2 - на этом этапе узнал о существовании ILIKE :)
query_6_1 = f'''select
    v.name as "name_vac",
    count(v.name) as "cnt_vac"
from
    public.vacancies v
WHERE v.name ILIKE '%данн%' or v.name ILIKE '%data%'
group by v.name 
    '''

In [59]:
# результат запроса
df = pd.read_sql_query(query_6_1, connection)
#df
df['cnt_vac'].sum()

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\338273320.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_1, connection)

np.int64(1771)

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста? 
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.

In [60]:
# текст запроса
# Работаю с фильтом Вакансии для начинающего дата-сайентиста и добавил условия в фильтр по Джуну.
query_6_2 = f'''select
    v.name as "name_vac",
    count(v.name) as "Junior"
from
    public.vacancies v
WHERE (v.name ILIKE '%data scientist%'
    or v.name ILIKE '%data science%' 
    or v.name ILIKE '%исследователь данных%'
    or v.name ILIKE '%machine learning%'
    or v.name ILIKE '%машинн%обучен%%' 
    or (v.name ILIKE '%ML%' and v.name not ILIKE '%HTML%'))
    and (v.name ILIKE '%junior%' or v.experience = 'Нет опыта' or v.employment = 'Стажировка')
group by v.id 
    '''

In [61]:
# результат запроса
df = pd.read_sql_query(query_6_2, connection)
#df
df['Junior'].sum()

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\3464793945.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_2, connection)

np.int64(51)

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [62]:
# текст запроса
# Работаю с фильтом Вакансии для начинающего дата-сайентиста, но в фильтр добавил условия уже по SQL.
query_6_3 = f'''select
    v.name as "name_vac",
    count(v.name) as "cnt_name"
from
    public.vacancies v
WHERE (v.name ILIKE '%data scientist%'
    or v.name ILIKE '%data science%' 
    or v.name ILIKE '%исследователь данных%'
    or v.name ILIKE '%machine learning%'
    or v.name ILIKE '%машинн%обучен%%' 
    or (v.name ILIKE '%ML%' and v.name not ILIKE '%HTML%'))
    and (v.key_skills ILIKE '%SQL%' or v.key_skills ILIKE'postgres')
group by v.id 
    '''

In [63]:
# результат запроса
df = pd.read_sql_query(query_6_3, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\3794299702.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_3, connection)

                                              name_vac  cnt_name
0                   Java Разработчик (направление AML)         1
1     Руководитель подразделения разработки (Teamlead)         1
2                              Junior+ CV/ML developer         1
3    Разработчик Golang/Python в команду аналитики ...         1
4      Backend- разработчик (Middle/Senior-TeamLeader)         1
..                                                 ...       ...
224  Аналитик/Аналитик данных (Data Analyst|Data Sc...         1
225  Junior Data Scientist (математик-аналитик) уда...         1
226                        Start Teamlead (начинающий)         1
227                        ML инженер / Data Scientist         1
228                         Специалист по Data Science         1

[229 rows x 2 columns]

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [64]:
# текст запроса
# Логика аналогичнf заданию выше, но в фильтр добавил условия Python.
query_6_4 = f'''select
    v.name as "name_vac",
    count(v.name) as "cnt_name"
from
    public.vacancies v
WHERE (v.name ILIKE '%data scientist%'
    or v.name ILIKE '%data science%' 
    or v.name ILIKE '%исследователь данных%'
    or v.name ILIKE '%machine learning%'
    or v.name ILIKE '%машинн%обучен%%' 
    or (v.name ILIKE '%ML%' and v.name not ILIKE '%HTML%'))
    and (v.key_skills ILIKE '%Python%' )
group by v.name 
    '''

In [65]:
# результат запроса
df = pd.read_sql_query(query_6_4, connection)
df['cnt_name'].sum()

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\3874216637.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_4, connection)

np.int64(357)

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [66]:
# текст запроса
# Воспользовался подсказкой. Ключевые навыки разделены символами табуляции. В SQL этот символ обозначается как CHR(9) - ЗАПОМНИТЬ
query_6_5 = f'''select
    round(AVG(CHAR_LENGTH(v.key_skills) - CHAR_LENGTH(replace(v.key_skills, CHR(9), '')) +1), 2) as "cnt_words"
from
    public.vacancies v
WHERE (v.name ILIKE '%data scientist%'
    or v.name ILIKE '%data science%' 
    or v.name ILIKE '%исследователь данных%'
    or v.name ILIKE '%machine learning%'
    or v.name ILIKE '%машинн%обучен%%' 
    or (v.name LIKE '%ML%' and v.name not ILIKE '%HTML%'))
    and v.key_skills is not NULL 
    '''

In [67]:
# результат запроса
df = pd.read_sql_query(query_6_5, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\3654210517.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_5, connection)

   cnt_words
0       6.41

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*). 

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа.

In [68]:
# текст запроса
# Для выполнения условия по расчетусредней ЗП для DS, воспользовался конструкцией CASE... ELSE...END 
# Так же в случае NULL по признакам ЗП применил COALESCE (плюс при отсутствии обоих значений по ЗП подставляем 0). Далле уже знакомые фильтры.
query_6_6 = f'''select
    experience,
    ROUND(AVG
    (CASE 
    WHEN v.salary_from IS NOT NULL AND v.salary_to IS NOT NULL THEN (v.salary_from + v.salary_to) / 2.0
    ELSE COALESCE(v.salary_from, v.salary_to, 0)
    END), 0) as "AVG_Salary"
FROM 
    public.vacancies v
WHERE (v.name ILIKE '%data scientist%'
    or v.name ILIKE '%data science%' 
    or v.name ILIKE '%исследователь данных%'
    or v.name ILIKE '%machine learning%'
    or v.name ILIKE '%машинн%обучен%%' 
    or (v.name LIKE '%ML%' and v.name not ILIKE '%HTML%'))
    and (v.salary_from is not NULL or v.salary_to is not NULL)
group by v.experience   
    '''

In [70]:
# результат запроса
df = pd.read_sql_query(query_6_6, connection)
df

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_5828\519194770.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_6, connection)

           experience  AVG_Salary
0           Нет опыта     74643.0
1  От 1 года до 3 лет    139675.0
2       От 3 до 6 лет    243115.0

In [ ]:
# Закрываю соединение с БД
connection.close()

***

In [ ]:
# выводы по предметному анализу
# 1. Количество вакансии связанных с DS составляет 3,5%. На фоне того, что 15% от бщего количества работодателей в качестве своей сферы деятельности 
# указали Разработка программного обеспечения.
# значение в 3,5% невелико. Но учитывая рост потребности в обработке/аналитеке Больших данных - предполагаю, что доля DS будет расти. 

# 2. Доля вакансий связанных с DS для начинающего дата-сайентиста - крайне малая, всего 2,9% (51 предложение). 
# Это говорит о том, что работодатели заинтересованы в квалифицированных кадрах. И начинающим DS будет сложно найти работу :)

# 3. Знание для DS - SQL или postgres является важным ключевым навыком с долей в 13%. 
# Соискателям стоит это учесть, также знание SQL будет плюсом особенно для новичков при поиске работы.

# 4. Знание для DS языка Python также является важным ключевым навыком с долей в 20%. 
# Объединия данный навык с вышуепомянутыми выше - можно сказать, что это одни из базовых навыков для DS.

# 5. В среднем около 6 ключевых навыков указывают в вакансиях для DS. 
# Но здесь стоит отметить, что зная Python, SQL это уже 1/3, 
# еще 1/3 ключевых навыков изучается параллельно с Python, SQL и остается еще 1/3 которую сосискатель может спокойно изучить/подтянуть.
# т.е. сами требования со стороны работодателя разумны и исполнимы.

# 6.Размер заработной платы для DS с учетом опыта - показывает, что даже без опыта соискатель может претендовать на хорошый базовый уровень зп. 
# Но важнее то, что с опытом уровень зп значительно возрастает (вторая ступень по зп стартует уже от 1 года).

# Общий вывод по проекту

In [ ]:
# подведем итог исследования, обобщите выводы
# здесь можно (это будет плюсом) провести дополнительные исследования данных, сделать прогнозы, продумать варианты продолжения исследования

### **ЧАСТЬ - 1**
* **Общее число вакансий** в объме **49 197** учитывая масштабы страны, количество работодателей, широкий охват, как по регионам так и по направлениям сфер деятельности на мой взгляд **небольшое**. Возможно это только часть данных (огрначенная по каким либо признакам) или данные за какой-то короткий (моментный) период или что-то еще.


### **ЧАСТЬ - 2** 
* Самое **Большое количество вакансий** приходятся на Москву и Санкт-Петербург. Предполагаю, что эти города выступают, как некие центры в которых зарегистрированы компании, 
а сотрудники им требуются либо в других регионах, либо данные работодатели предлагают удаленный режим работы. 

* Косвенно **удаленный режим работы** подтверждают данные о том, что удаленная работа находится на втором месте по условиям работодателей. 

* Далее **стоит отметить**, что удаленным форматом работы работодатель **увеличивает** количество потенциальных работников при выборе за счет большей географии, 
и даже поверхностно исследовав средний уровень ЗП в Москве, С-ПБ, городах миллиониках по сравнению с остальными регионами меньшей численностью. 
Мы можем наблюдать более **низкий уровень ЗП** в регионах с меньшей численностью, а это **хорошая экономия издержек** для работодателя. 

* Также вссе вышеописанное очень хорошо укладывается в **концепцию iT комп., ком. телекоммуникационного сектора, Банков**, спрос на услуги которых **растет**, 
у них в свою очередь **возрастают объемы работ**, спрос **на сотрудников** соответсвенно тоже растет, и при этом **издержки,** компании логично **хотят снизить**. 

* Поэтому Формат работы: **удаленная и полная занятость думаю будет расти.**

* Заполненные **на половину** поля с ЗП имеют **негавный момент.** В случае когда не заполнено поле **ЗП от...** 
Это не позволяет площадке **hh** формировать предложения своим сосискателям, а соискатели могут просто **не обратить** внимание на подобные вакансии, 
где отсуствует инфо по ЗП от ... В случает когда заполнено только **ЗП до ...** Это может вызвать у соискателя **разочарование** по фактически озвученной ЗП работодателем, 
да и сам работодатель в этом случае **впустую тратит время** на интервью с соискателями, т.к. сосискатель не примет его предложение из-за ложных ожиданий. 
Как предложение разработать **механизм стимулирования работодателя** к заполнению максимальной информациии о вакансии. 
Данное предложение также относится и к другим незаполненным полям в Анкете работодателя (так например более 1/3 не указали сферу деятельности компании). 

* Москва помимо количества **вакансий** лидирует и по количеству **работодателей** - это в свою очередь также подкрепляет мои выводы выше 
в части увеличения доли удаленного формата работы, сокращения издержек. 

### **ЧАСТЬ - 3**
* В подтверждение **роста спроса на iT** продукты говорят следующие данные: 

* В **первой пятерке** работодателей по количеству ванкансий мы наблюдаем IT-отрасль, телекоммуникационную, банковский сектор

* уже **15%** от бщего количества работодателей в качестве своей сферы деятельности занимаются Разработкой программного обеспечения

* по количеству опубликованных вакансий по регионам также **лидирующие** первые 2 позиции занимают **iT** компания и **Телекоммуникационный сектор**

### **ЧАСТЬ - 4**
* Учитывая **небольшой объем** вакансий по направлению DS всего **3,5%** от общей массы iT-вакансий, как результат мы имеем **маленькое предложение** 
и для начинающих **junior** специалистов. Т.е. новичку будет **сложнее** найти работу. Безусловно это минус. 
В то же время ситуация может быть скорректирована **в лучшую сторону** ростом направления работы с большими данными.

* Большое количество **ключевых навыков** к позиции DS говорит о том, что уже на базовом уровне требуется изучить много областей/тем, чтобы овладеть специальностью DS. 
Другими словами вход в область DS требует **углубленного серьезного** подхода со стороны сосискателя.

* Безусловным **большим плюсом** является **оплата** на позициях DS. На начальном уровне она примерно равна с остальными специализациями, 
но начия уже с наличия опыта от **1 года** уровень ЗП растет не только в цифрах, но по отношению к другим специализациям. 
А с наличием опыта **от 3 лет** отрыв по ЗП **увеличивается,** так к примеру в сравнении с позицией программиста 1С ЗП специалиста DS выше в среднем минимум на 35%.